networks:
  internal:
    driver: bridge
    
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/plexpy:/config
      - /var/log/plexpy:/logs:ro
      - ${USERDIR}/docker/certs:/certs
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ${USERDIR}/docker/lidarr:/config
      - /mnt:/media
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/certs:/certs
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/certs:/certs
      - /mnt:/media
    ports:
      - 9117:9117
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    # build: /etc/environment
    #image: linuxserver/sonarr:latest
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - /opt/appdata/sma:/usr/local/sma/config
      - ${USERDIR}/docker/sonarr:/config
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/certs:/certs
      - "/mnt/plex1/plex/tv shows:/tv"
      - /mnt:/media
    ports:
        - "8989:8989"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    # build: /etc/environment
    #image: linuxserver/radarr:latest
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - /opt/appdata/sma:/usr/local/sma/config
      - ${USERDIR}/docker/radarr:/config
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/certs:/certs
      - "/mnt/plex1/plex/tv shows:/tv"
      - /mnt:/media
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/bazarr/config:/config
      - /mnt:/media
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/overseer/config:/config
      - /mnt:/media
    ports:
      - 5055:5055
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/prowlarr:/config
      - /mnt:/media
    ports:
      - 9696:9696
    restart: unless-stopped
    
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=dd08a83eea6404928dc407b5bb31a78069bddbd4dba9bf6c486e898cae6199b6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${USERDIR}/docker/homarr/appdata:/appdata
    ports:
      - '7575:7575'

  flaresolverr:
    image: 	ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - '8191:8191'